CREATE TABLE public.adm_unit (
	adm_unit_id int4 NOT NULL GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" text NULL,
	CONSTRAINT adm_unit_pk PRIMARY KEY (adm_unit_id)
);